### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by slobo**
allow github to do syntax highlighting

### CODE REVIEW

**Comment by felliott** [comment]
Hey @slobo,

Thanks for the PR!  I'm interested in this, but `README.md` is generated by the build-and-release tool I use, [Minilla](https://metacpan.org/release/Minilla).  Minilla currently uses Pod::Markdown to generate the readme, and I don't see an easy way to substitute in Pod::Markdown::Github.  I'm currently at YAPC::NA, I'll spend a little time to see if I can figure it out.  If you're around and would like to work on this, please let me know!

Cheers,
Fitz

**Comment by felliott** [comment]
I've put in an RFC to Minilla for this: https://github.com/tokuhirom/Minilla/issues/161.

Cheers,
Fitz

**Comment by slobo** [comment]
I wondered if if was auto generated, and thanks for pointing out Minilla to me :)

**Comment by felliott** [comment]
Just a followup: tokuhirom took my patch for using alternative Markdown processors, so once that's released I'll start adding github syntax highlighting to my README.md.  Thanks for getting this going!

Cheers,
Fitz

**Pull request closed without merging**
